import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Package, CheckCircle, Clock, Truck, Home, MapPin, Instagram, Palette, Printer, Award, Copy, Check, FileText, ArrowRight } from 'lucide-react';
import db from '../services/database.js';
import { PromoBanner } from '../components/PromoBanner';
import PaymentGateway from '../services/PaymentGateway.js';
import { QRCodeSVG } from 'qrcode.react';

export function OrderTracking() {
  const { id } = useParams();
  const [order, setOrder] = useState(null);
  const [designs, setDesigns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [companyConfig, setCompanyConfig] = useState({ companyName: 'Estúdio Criativo', logoBase64: null, instagram: '' });
  const [pixData, setPixData] = useState(null);
  const [pixError, setPixError] = useState('');
  const [isRefunding, setIsRefunding] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const fetchOrder = async () => {
      try {
        const allOrders = await db.getAll('orders');
        const allDesigns = await db.getAll('designs') || [];
        // Handle string/int matching
        const found = allOrders.find(o => String(o.id) === String(id));
        setOrder(found || null);
        setDesigns(allDesigns);

        // Fetch company branding
        try {
            const settings = await db.getById('settings', 'global');
            if (settings) {
                setCompanyConfig(settings);
                document.title = `${settings.tabTitle || settings.companyName || 'Ateliê'} | Rastreio`;
            }
        } catch(e) { console.error("Could not fetch settings", e); }
      } catch (error) {
        console.error("Error fetching order for tracking:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchOrder();
  }, [id]);

  useEffect(() => {
    if (order && order.paymentMethod === 'pix' && order.paymentStatus !== 'Pago' && order.ecommerceOrigin) {
        
        // Zero-API optimization: Check if it was explicitly generated by Checkout atomically.
        if (order.pixQrCode) { // Only accept the valid EMV string (not base64 image strings)
            setPixData({ qr_code: order.pixQrCode, transaction_id: order.mpPaymentId });
            return; // Completely bypass creating a duplicate transaction which pollutes MP.
        }
        
        PaymentGateway.createPixTransaction(order).then(res => {
            if (res && res.success) {
                setPixData(res);
            } else {
                setPixError(res?.error || 'Erro desconhecido ao gerar o Pix.');
                console.error("PaymentGateway Error:", res);
            }
        }).catch(err => {
            setPixError(err.message || String(err));
        });
    }
  }, [order]);

  const handleCopyPix = () => {
      if (pixData && pixData.qr_code) {
          navigator.clipboard.writeText(pixData.qr_code);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
      }
  };

  const handleRequestCancellation = async () => {
    if(!window.confirm("Você tem certeza que deseja cancelar sua compra?\n\nO valor será estornado integralmente para a mesma conta que você usou para pagar.")) return;
    
    try {
        setIsRefunding(true);
        const mpId = order.mpPaymentId || order.transaction_id;
        
        // CENÁRIO 1: Já pago. Chama a API de Refund e DELEGA TUDO pro Webhook Inviolável para evitar duplicação!
        if ((order.paymentStatus === 'Pago' || order.paymentStatus === 'Recebido') && mpId) {
            const isLocalhost = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';
            const baseUrl = isLocalhost ? 'http://localhost:5173' : 'https://ateliecarol.vercel.app';
            
            const res = await fetch(`${baseUrl}/api/refund`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ paymentId: mpId })
            });
            
            if (!res.ok) {
                const data = await res.json();
                console.error("MP Error:", data);
                if (data.details?.status !== 400 && data.details?.message?.indexOf("already refunded") === -1) {
                    throw new Error("O Banco não autorizou o estorno automático neste momento. Procure o Suporte no WhatsApp.");
                }
            }
            
            // Sucesso! A API do Vercel Webhook fará TUDO: estorno contábil duplo, voltar estoque e mudar status.
            alert("Ordem de Estorno enviada ao Banco! Seu status será atualizado automaticamente via Webhook Cloud.");
            window.location.reload();
            return; 
        }
        
        // CENÁRIO 2: AINDA NÃO PAGO (Apenas Abandono de Carrinho Seguro)
        // 1. Marca como Cancelado localmente
        await db.update('orders', order.id, {
            status: 'Cancelado',
            cancelDate: new Date().toISOString()
        });
        
        // 2. Devolve Estoque Imediatamente (Anti-Sequestro)
        if (order.cartItems && order.cartItems.length > 0) {
            const allProducts = await db.getAll('products') || [];
            for (const item of order.cartItems) {
                const product = allProducts.find(p => String(p.id) === String(item.productId));
                if (product && product.stock !== undefined) {
                    await db.update('products', product.id, {
                        stock: product.stock + (Number(item.quantity) || 1)
                    });
                }
            }
        }
        
        await db.create('system_notifications', {
            type: 'ORDER_CANCELLED',
            message: `O cliente ${order.customer} desistiu/cancelou autonomamente a Reserva #${String(order.id).substring(0,8)} antes do pagamento. Estoque Restaurado.`,
            data: order.id,
            timestamp: new Date().toISOString(),
            read: false
        });

        alert("Sua reserva foi cancelada com sucesso!");
        window.location.reload();
        
    } catch(err) {
        alert("Falha Operacional: " + err.message);
    } finally {
        setIsRefunding(false);
    }
  };

  const handleSimulatePayment = async () => {
      // Mock para testarmos o fluxo local sem webhook verdadeiro
      await PaymentGateway.handleWebhookSimulated(order.id, 'approved_mock');
      alert("Pagamento processado em ambiente de teste!");
      window.location.reload();
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', backgroundColor: '#f8fafc' }}>
        <div style={{ animation: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite', color: 'var(--primary)', fontWeight: 'bold' }}>
          Consultando a magia...
        </div>
      </div>
    );
  }

  if (!order) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', backgroundColor: '#f8fafc', padding: '20px', textAlign: 'center' }}>
        <Package size={64} style={{ color: '#cbd5e1', marginBottom: '20px' }} />
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#334155' }}>Pedido não encontrado</h2>
        <p style={{ color: '#64748b', marginTop: '10px' }}>Verifique se o link está correto ou entre em contato com o ateliê.</p>
      </div>
    );
  }

  const steps = [
    { id: 'Novo', icon: <Clock size={24} />, label: 'Na Fila', desc: 'Aguardando início' },
    { id: 'pending', icon: <Palette size={24} />, label: 'Arte & Design', desc: 'Em diagramação ou análise' },
    { id: 'printing', icon: <Printer size={24} />, label: 'Na Produção', desc: 'Imprimindo & Acabamento' },
    { id: 'completed', icon: <Award size={24} />, label: 'Pronto!', desc: 'Finalizado com amor' }
  ];

  const getActiveIndex = (currentStep, itemStatus) => {
      let index = 0; // "Na Fila"
      if (currentStep === 'pending') index = 0;
      if (currentStep === 'design') index = 1;
      if (currentStep === 'printing' || currentStep === 'finishing' || currentStep === 'cutting') index = 2;
      if (currentStep === 'completed' || itemStatus === 'Concluído' || itemStatus === 'Pronto para Retirada') index = 3;
      return index;
  };

  const itemsToTrack = (order.cartItems && order.cartItems.length > 0) 
      ? order.cartItems.map((item, idx) => {
          const design = item.designId ? designs.find(d => String(d.id) === String(item.designId)) : null;
          return {
              id: idx,
              name: item.name || 'Produto Base',
              quantity: item.quantity || 1,
              productionStep: item.productionStep || order.productionStep || 'Novo',
              status: item.productionStep === 'completed' ? 'Concluído' : order.status,
              designId: item.designId || null,
              designName: item.designName || design?.name || null,
              designThumb: design?.imageBase64 || design?.thumbnail || design?.image || null,
          };
      })
      : [{
          id: 0,
          name: order.productName || 'Itens do Pedido',
          quantity: order.items || 1,
          productionStep: order.productionStep || 'Novo',
          status: order.status,
          designId: null,
          designName: null,
          designThumb: null,
      }];

  const isAllCompleted = itemsToTrack.every(i => getActiveIndex(i.productionStep, i.status) === 3);

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#fdfcfe', display: 'flex', justifyContent: 'center', padding: '40px 20px', fontFamily: 'var(--font-primary)' }}>
      <div style={{ maxWidth: '480px', width: '100%' }}>
        
        {/* Header Block */}
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            {companyConfig.logoBase64 && (
                <img src={companyConfig.logoBase64} alt="Company Logo" style={{ maxWidth: '120px', maxHeight: '120px', margin: '0 auto 16px', display: 'block', objectFit: 'contain' }} />
            )}
            <h1 style={{ fontSize: '1.8rem', fontWeight: 800, color: 'var(--primary)', marginBottom: '8px' }}>
                {companyConfig.companyName || 'Ateliê Estúdio Criativo'}
            </h1>
            <p style={{ color: '#64748b' }}>Ateliê Carol 🎀</p>
        </div>

        {/* Card */}
        <div style={{ backgroundColor: 'white', borderRadius: '16px', padding: '30px', boxShadow: '0 4px 20px rgba(0,0,0,0.05)', border: '1px solid #f1f5f9' }}>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', paddingBottom: '20px', borderBottom: '1px dashed #e2e8f0' }}>
             <div>
                <p style={{ fontSize: '0.8rem', textTransform: 'uppercase', fontWeight: 700, color: '#94a3b8', letterSpacing: '0.05em' }}>Pedido #{order.id?.toString().substring(0,8)}</p>
                <h2 style={{ fontSize: '1.25rem', fontWeight: 700, color: '#334155', marginTop: '4px' }}>
                    Olá, {order.customer?.split(' ')[0]}!
                </h2>
             </div>
             <div style={{ backgroundColor: '#f0fdf4', padding: '8px 12px', borderRadius: '8px', color: '#16a34a', fontWeight: 600, fontSize: '0.85rem' }}>
                {isAllCompleted ? 'Finalizado' : 'Em Andamento'}
             </div>
          </div>

          {order.paymentMethod === 'pix' && order.paymentStatus !== 'Pago' && pixData && (
              <div style={{ backgroundColor: '#f8fafc', border: '2px dashed #94a3b8', borderRadius: '16px', padding: '24px', textAlign: 'center', marginBottom: '30px' }}>
                  <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#334155', marginBottom: '16px' }}>Escaneie para Pagar</h3>
                  <div style={{ backgroundColor: 'white', display: 'inline-block', padding: '16px', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)', marginBottom: '16px' }}>
                     <QRCodeSVG value={pixData.qr_code} size={150} />
                  </div>
                  <p style={{ fontSize: '0.9rem', color: '#64748b', marginBottom: '16px' }}>Ou copie o código Copia-e-Cola abaixo:</p>
                  
                  <div style={{ display: 'flex', gap: '8px' }}>
                      <input 
                         type="text" 
                         readOnly 
                         value={pixData.qr_code} 
                         style={{ flex: 1, padding: '12px', borderRadius: '8px', border: '1px solid #cbd5e1', backgroundColor: 'white', color: '#475569', fontSize: '0.8rem' }}
                      />
                      <button 
                         onClick={handleCopyPix}
                         style={{ backgroundColor: copied ? '#10b981' : 'var(--primary)', color: 'white', border: 'none', padding: '0 16px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 700, transition: 'all 0.2s' }}
                      >
                         {copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? 'Copiado!' : 'Copiar'}
                      </button>
                  </div>
                  
                  <button 
                      onClick={handleSimulatePayment}
                      style={{ marginTop: '20px', backgroundColor: 'transparent', border: '1px solid #94a3b8', color: '#64748b', padding: '8px 16px', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer' }}
                  >
                      Avisar que já paguei (Simular Webhook)
                  </button>
              </div>
          )}

          {order.paymentMethod === 'pix' && order.paymentStatus !== 'Pago' && pixError && !pixData && (
              <div style={{ backgroundColor: '#fff1f2', border: '2px dashed #fecdd3', borderRadius: '16px', padding: '24px', textAlign: 'center', marginBottom: '30px' }}>
                  <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#be123c', marginBottom: '8px' }}>Pix Temporariamente Indisponível</h3>
                  <p style={{ fontSize: '0.9rem', color: '#881337', marginBottom: '0' }}>Ocorreu um erro ao conectar com o banco: <strong>{pixError}</strong></p>
              </div>
          )}

          {/* Módulo B2C Logística & Fiscal */}
          {(order.trackingCode || order.invoiceUrl) && (
              <div style={{ backgroundColor: '#faf5ff', border: '1px solid #e9d5ff', borderRadius: '16px', padding: '24px', marginBottom: '30px', animation: 'fadeIn 0.5s ease-out' }}>
                  <h3 style={{ fontSize: '1.05rem', fontWeight: 800, color: '#6b21a8', margin: '0 0 16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <Truck size={20} /> Entrega & Recibos
                  </h3>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                      {order.trackingCode && (
                          <div style={{ backgroundColor: '#ffffff', border: '1px solid #d8b4fe', padding: '16px', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
                              <div>
                                  <p style={{ fontSize: '0.75rem', fontWeight: 700, color: '#9333ea', margin: 0, textTransform: 'uppercase' }}>Código de Rastreio</p>
                                  <p style={{ fontSize: '1.1rem', fontWeight: 800, color: '#334155', margin: '4px 0 0' }}>{order.trackingCode}</p>
                              </div>
                              <a 
                                  href={`https://linketrack.com/track?codigo=${order.trackingCode}`} 
                                  target="_blank" 
                                  rel="noopener noreferrer"
                                  style={{ backgroundColor: '#9333ea', color: 'white', padding: '8px 16px', borderRadius: '8px', textDecoration: 'none', fontWeight: 700, fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px', transition: 'all 0.2s', boxShadow: '0 2px 4px rgba(147, 51, 234, 0.2)' }}
                              >
                                  Acompanhar Pacote <ArrowRight size={16} />
                              </a>
                          </div>
                      )}
                      
                      {order.invoiceUrl && (
                          <div style={{ backgroundColor: '#ffffff', border: '1px solid #e2e8f0', padding: '16px', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
                              <div>
                                  <p style={{ fontSize: '0.85rem', fontWeight: 700, color: '#475569', margin: 0, display: 'flex', alignItems: 'center', gap: '6px' }}><FileText size={16}/> Comprovante Fiscal / Recibo</p>
                              </div>
                              <a 
                                  href={order.invoiceUrl} 
                                  target="_blank" 
                                  rel="noopener noreferrer"
                                  style={{ backgroundColor: '#f1f5f9', color: '#334155', padding: '8px 16px', borderRadius: '8px', textDecoration: 'none', fontWeight: 700, fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px', border: '1px solid #cbd5e1' }}
                              >
                                  Abrir PDF
                              </a>
                          </div>
                      )}
                  </div>
              </div>
          )}

          {/* Área de Risco Reversa: Cancelamento Público (Até antes da produção) */}
          {(order.status === 'Novo' || order.status === 'Design / Arte' || order.status === 'Pendente') && (
              <div style={{ padding: '20px', backgroundColor: '#fff', border: '1px solid #e2e8f0', borderRadius: '12px', marginBottom: '30px', textAlign: 'center' }}>
                  <p style={{ color: '#64748b', fontSize: '0.85rem', marginBottom: '12px' }}>
                      Se arrependeu da compra ou houve algum imprevisto? Você pode cancelar seu pedido até o início da produção.
                  </p>
                  <button 
                      onClick={handleRequestCancellation}
                      disabled={isRefunding}
                      style={{ backgroundColor: 'white', color: '#ef4444', border: '1px solid #fca5a5', padding: '10px 24px', borderRadius: '8px', cursor: isRefunding ? 'not-allowed' : 'pointer', fontWeight: 600, transition: 'all 0.2s', opacity: isRefunding ? 0.6 : 1 }}
                  >
                      {isRefunding ? 'Processando Autenticação...' : 'Solicitar Cancelamento e Estorno'}
                  </button>
              </div>
          )}

          <p style={{ color: '#475569', fontSize: '0.95rem', marginBottom: '30px', lineHeight: '1.6' }}>
             Seu pedido contendo <strong>{order.items} iten(s)</strong> está passando pela nossa linha de produção carinhosa. Veja o status de cada item abaixo:
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
              {itemsToTrack.map((item, idx) => {
                  const activeIndex = getActiveIndex(item.productionStep, item.status);
                  
                  return (
                      <div key={item.id} style={{ paddingTop: idx > 0 ? '40px' : '0', borderTop: idx > 0 ? '1px dashed #e2e8f0' : 'none' }}>
                          <h3 style={{ margin: 0, fontSize: '1.05rem', fontWeight: 700, color: '#334155', marginBottom: item.designId ? '16px' : '30px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                              <Package size={20} style={{ color: 'var(--primary)' }} /> {item.quantity}x {item.name}
                          </h3>

                          {/* Design / Modelo vinculado */}
                          {item.designId && (
                              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', backgroundColor: '#faf5ff', border: '1px solid #e9d5ff', borderRadius: '12px', padding: '12px 16px', marginBottom: '24px' }}>
                                  {item.designThumb ? (
                                      <img
                                          src={item.designThumb}
                                          alt={item.designName}
                                          style={{ width: '56px', height: '56px', objectFit: 'cover', borderRadius: '8px', flexShrink: 0, border: '2px solid #d8b4fe', boxShadow: '0 2px 8px rgba(124,58,237,0.15)' }}
                                      />
                                  ) : (
                                      <div style={{ width: '56px', height: '56px', backgroundColor: '#ede9fe', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                          <Palette size={24} color="#8b5cf6" />
                                      </div>
                                  )}
                                  <div>
                                      <div style={{ fontSize: '0.7rem', fontWeight: 700, color: '#7c3aed', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '2px' }}>Arte / Molde Vinculado</div>
                                      <div style={{ fontSize: '0.95rem', fontWeight: 700, color: '#4c1d95' }}>{item.designName || `Modelo #${item.designId}`}</div>
                                      <div style={{ fontSize: '0.78rem', color: '#8b5cf6', marginTop: '2px' }}>Este molde está sendo utilizado na produção do seu item.</div>
                                  </div>
                              </div>
                          )}
                          
                          {/* Vertical Timeline */}
                          <div style={{ position: 'relative' }}>
                             {/* Background Line */}
                             <div style={{ position: 'absolute', left: '20px', top: '24px', bottom: '24px', width: '2px', backgroundColor: '#e2e8f0', zIndex: 0 }}></div>
                             
                             {/* Active Line Progress */}
                             <div style={{ 
                                 position: 'absolute', left: '20px', top: '24px', width: '2px', 
                                 backgroundColor: 'var(--primary)', zIndex: 1,
                                 height: `${(activeIndex / (steps.length - 1)) * 100}%`,
                                 transition: 'height 1s ease-in-out'
                             }}></div>

                             {steps.map((step, index) => {
                                 const isCompleted = index <= activeIndex;
                                 const isActive = index === activeIndex;
                                 return (
                                     <div key={step.id} style={{ display: 'flex', gap: '20px', alignItems: 'flex-start', marginBottom: index === steps.length - 1 ? '0' : '40px', position: 'relative', zIndex: 2 }}>
                                         <div style={{ 
                                             width: '42px', height: '42px', borderRadius: '50%', display: 'flex', justifyContent: 'center', alignItems: 'center', flexShrink: 0,
                                             backgroundColor: isActive ? 'var(--primary)' : (isCompleted ? '#f1f5f9' : 'white'),
                                             color: isActive ? 'white' : (isCompleted ? 'var(--primary)' : '#cbd5e1'),
                                             border: `2px solid ${isCompleted ? 'var(--primary)' : '#e2e8f0'}`,
                                             transition: 'all 0.5s ease',
                                             boxShadow: isActive ? '0 0 0 4px rgba(99, 102, 241, 0.2)' : 'none'
                                         }}>
                                             {isCompleted && !isActive ? <CheckCircle size={20} /> : step.icon}
                                         </div>
                                         <div style={{ paddingTop: '8px' }}>
                                             <h4 style={{ margin: 0, fontSize: '1.05rem', fontWeight: isActive ? 700 : 600, color: isActive ? '#1e293b' : (isCompleted ? '#334155' : '#94a3b8') }}>
                                                 {step.label}
                                             </h4>
                                             <p style={{ margin: 0, fontSize: '0.85rem', color: '#64748b', marginTop: '4px' }}>
                                                 {step.desc}
                                             </p>
                                         </div>
                                     </div>
                                 );
                             })}
                          </div>
                      </div>
                  );
              })}
          </div>
        </div>
        
        <PromoBanner promoConfig={companyConfig?.promoBanner} companyConfig={companyConfig} />

        <div style={{ textAlign: 'center', marginTop: '30px', color: '#94a3b8', fontSize: '0.8rem' }}>
            Atualizado automaticamente em tempo real.<br/>
            &copy; {new Date().getFullYear()} {companyConfig.companyName || 'Estúdio Criativo'}
        </div>

      </div>
    </div>
  );
}
